# Generated by Django 5.2.1 on 2025-06-14 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0004_expensecategory_expense'),
    ]

    operations = [
        migrations.AddField(
            model_name='reminder',
            name='is_bulk',
            field=models.BooleanField(default=False),
        ),
    ]
