# Generated by Django 5.2.1 on 2025-07-05 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0009_customer_created_by_reminder_sent_by'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='reminder',
            name='customers_r_status_4a3e24_idx',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='reminder',
            name='sent_by',
        ),
    ]
