# Generated by Django 5.2.1 on 2025-07-23 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0012_remove_customer_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceplan',
            name='monthly_limit',
            field=models.PositiveIntegerField(default='1'),
        ),
    ]
